package rest;

import java.util.ArrayList;
import java.util.Date;

public class DMRCar{

    public String regNr;
    public String stelNr;
    public String status;
    public String statusDato;
    public String foersteRegistreringDato;
    public String bilLeaset;
    public String leasingGyldigFra;
    public String leasingGyldigTil;
    public String leasingPeriode;
    public String foersteRegistreringDatoFormateret;
    public String koeretoejArtNavn;
    public String koeretoejAnvendelseNavn;
    public String totalVaegt;
    public String egenVaegt;
    public String vogntogVaegt;
    public String koereklarVaegtMinimum;
    public String tekniskTotalVaegt;
    public String paahaengVognTotalVaegt;
    public String akselAntal;
    public String siddepladserMinimum;
    public String tilkoblingsmulighed;
    public String tilkoblingsvaegtUdenBremser;
    public String tilkoblingsvaegtMedBremser;
    public String ncapTest;
    public String koeretoejstand;
    public String maerkeTypeNavn;
    public String modelTypeNavn;
    public String variantTypeNavn;
    public String farveTypeNavn;
    public String typeGodkendelsesNummer;
    public String modelAar;
    public String karrosseriTypeNavn;
    public String motorSlagVolumen;
    public String motorStoerrelse;
    public String motorStoersteEffekt;
    public String motorHestekraefter;
    public String motorKmPerLiter;
    public String motorKilometerstand;
    public String motorElektriskForbrug;
    public String drivkraftTypeNavn;
    public ArrayList<String> koeretoejUdstyrSamling;
    public String motorMaerkning;
    public String maksimumHastighed;
    public String motorCylinderAntal;
    public String antalDoere;
    public String faelgDaek;
    public String sporviddenForrest;
    public String sporviddenBagest;
    public String stelNummerAnbringelse;
    public String passagerAntal;
    public String traekkendeAksler;
    public String akselAfstand;
    public String stoersteAkselTryk;
    public String miljoeOplysningCO2Udslip;
    public String miljoeOplysningEmissionCO;
    public String miljoeOplysningEmissionHCPlusNOX;
    public String miljoeOplysningEmissionNOX;
    public String miljoeOplysningPartikelFilter;
    public String miljoeOplysningRoegtaethed;
    public String miljoeOplysningRoegtaethedOmdrejningstal;
    public String miljoeOplysningPartikler;
    public String motorKoerselStoej;
    public String motorStandStoej;
    public String motorStandStoejOmdrejningstal;
    public String normTypeNavn;
    public String adressePostNummer;
    public String adressePostNummerBy;
    public String koeretoejId;
    public String sekundaerStatus;
    public String sekundaerStatusDato;

}
